/* Generated by Yosys 0.47+121 (git sha1 98b4affc4, g++ 13.2.0-23ubuntu4 -fPIC -O3) */

module sequence_detector(clk, reset, din, detected);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  input clk;
  wire clk;
  output detected;
  reg detected;
  input din;
  wire din;
  input reset;
  wire reset;
  reg [6:0] state;
  assign _08_ = din & ~(reset);
  assign _09_ = ~(state[5] | state[0]);
  assign _10_ = _08_ & ~(_09_);
  assign _06_ = _10_ | reset;
  assign _07_ = reset | ~(state[3]);
  assign _11_ = reset | din;
  assign _12_ = ~(state[1] | state[0]);
  assign _13_ = state[3] | state[2];
  assign _14_ = _12_ & ~(_13_);
  assign _15_ = state[6] | state[4];
  assign _16_ = _15_ | ~(_14_);
  assign _03_ = _16_ & ~(_11_);
  assign _02_ = state[5] & ~(_11_);
  assign _17_ = ~(state[4] | state[3]);
  assign _01_ = _08_ & ~(_17_);
  assign _04_ = _08_ & state[1];
  assign _05_ = _08_ & state[2];
  assign _00_ = _08_ & state[6];
  always @(posedge clk)
    if (_07_) detected <= 1'h0;
    else detected <= din;
  always @(posedge clk)
    state[0] <= _06_;
  always @(posedge clk)
    state[1] <= _00_;
  always @(posedge clk)
    state[2] <= _01_;
  always @(posedge clk)
    state[3] <= _02_;
  always @(posedge clk)
    state[4] <= _03_;
  always @(posedge clk)
    state[5] <= _04_;
  always @(posedge clk)
    state[6] <= _05_;
endmodule
